### PR TITLE
Added a run() method and throws an error that it doesn't have it.

### PR DESCRIPTION
**Pull request by ohlookitsAugust**
// No description provided.

### CODE REVIEW

**Comment by YorkAARGH** [comment]
what would the purpose of this be?

**Comment by ohlookitsAugust** [comment]
People might forget to add a `async run()` method and it throw a error to add it.

**Comment by TaiweiLoh** [comment]
@ohlookitsAugust Maybe you need to disable ESLint rule no-unused-vars for the parameter. And fix the one indentation.
image
~~I hate codacy also, but it keeps code clean~~

**Comment by YorkAARGH** [comment]
Closed due to self implementation due to original author not correcting lint errors.

**Pull request closed without merging**
