### PR TITLE
Server name in daily.

### PR DESCRIPTION
**Pull request by TaiweiLoh**
Claim daily in server: \`${message.guild.name}\` add to reminder

### CODE REVIEW

**Comment by TaiweiLoh** [comment]
Haha forgot to change `'`'s into a `

**Comment by TaiweiLoh** [comment]
Someone can test this later. I have no time. PR Closed.

**Comment by YorkAARGH** [comment]
if this shit breaks @goatwithakb is to blame

**Comment by goatwithakb** [comment]
WHA WHO WHY I DIDNT TEST IT OG TESTED IT
PLEASE DONT HURT ME

**Pull request merged**
