### PR TITLE
Teeeeeeeeeny tiny fix

### PR DESCRIPTION
**Pull request by goatwithakb**
Set reminders if daily is already claimed

### CODE REVIEW

**Comment by Kolkies** [comment]
Nice idea

**Comment by YorkAARGH** [comment]
I've said it once, and I'll say it again, not sure why you want to add this functionality, as we have a reminder command as it is lol

**Comment by goatwithakb** [comment]
ease of use? Easier to type that than ?remind in 1 day to claim daily, plus ive seen users assume it will work that way, so why not add the functionality

**Comment by goatwithakb** [comment]
ease of use? Easier to type that than ?remind in 1 day to claim daily, plus ive seen users assume it will work that way, so why not add the functionality
(Although if you do plan to add it, give it a quick test first, I cant atm)

**Comment by goatwithakb** [comment]
i will stop dreaming now

**Pull request closed without merging**
